//@server = localhost
@server = 51.144.63.30

POST http://{{server}}:3000
Content-Type: application/json

{
    "device": {
        "deviceId": "device010"
    },
    "measurements": {
        "temperature": 22.31,
        "humidity": 18.5
    }
}

###

GET http://{{server}}:3000/deviceEnrollments

###

POST http://{{server}}:3000/deviceEnrollments
Content-Type: application/json

{
    "2cf7f12014700298": {
        "idScope": "0ne000B688E",
        "primaryKey": "+VXBA6/+nFWsgzxFvvF0cu4/IR0Gh/iNv/1vajQVEvWDTFIu9TAnv+fP9MaM9T2TbtcUWngiObk3xYBq546u5w==",
        "capabilityModelId": "urn:seeedstudio:sensecap:1"
  }
}