POST http://localhost:3000
content-type: application/json

{
    "device": {
        "deviceId": "device010"
    },
    "measurements": {
        "temperature": 22.31,
        "humidity": 18.5
    }
}